### ISSUE TITLE
[Feature Request] Common工具添加

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/javafxTool#1003]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

1. [ ] url编解码
2. [ ] base64编解码
3. [ ] aes加解密
4. [ ] 时间戳转换
5. [ ] 日期计算
6. [ ] OCR
7. [ ] 音视频转换文本
8. [ ] json解析
10. [ ] 正则表达式工具
11. [ ] 颜色代码转换工具
12. [ ] 转义工具
13. [ ] Http接口测试工具
14. [ ] 端口扫描工具
15. [ ] 图标生成工具
16. [ ] 图片压缩工具
17. [ ] 图片拆分工具

### Additional context

```[tasklist]
### TODO
- [ ] [JSON解析](https://github.com/unknowIfGuestInDream/javafxTool/issues/1008)
```

_No response_
